version: '3.6'

services:
  influxdb:
    build:
      context: ./Influx
    ports: 
      - '8086:8086'

  telegraf:
    build:
      context: ./Telegraf
    volumes:
      - ./Telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb

  grafana:
    build:
      context: ./Grafana
    ports:
    - '3000:3000'
    links:
      - influxdb
    depends_on:
      - influxdb

volumes:
  influxdb_data: {}
    
  
